name: 'Next semantic version'
description: Calculate the next semantic version for a GitHub release
inputs:
  branch: 
    description: The branch you want to pull the latest release version from
    required: false
  increment-type: 
    description: Select which version to increment (major, minor or patch)
    required: false
outputs: 
  next-semantic-version:
    description: The max version code in the play store for the app +1
    value: ${{ steps.version_code_increment.outputs.VALUE }}
runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v2
      with: 
        ref: ${{inputs.branch}}
    - uses: actions-ecosystem/action-get-latest-tag@v1
      id: get-latest-tag
    - name: Echo
      run: |
        echo ${{ steps.get-latest-tag.outputs.tag }}
      shell: bash
