name: 'Next semantic version'
description: Calculate the next semantic version for a GitHub release
inputs:
  branch: 
    description: The branch you want to pull the latest release version from
    required: false
  increment-type: 
    description: Select which version to increment (major, minor or patch)
    required: false
outputs: 
  next-semantic-version:
    description: The max version code in the play store for the app +1
    value: ${{ steps.version_code_increment.outputs.VALUE }}

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v2
      with: 
        ref: ${{inputs.branch}}
    - name: Get semantic version
      uses: valadas/get-release-branch-version@v1
        id: current-semantic-version
      - name: Dump the version info
        env:
          MAJOR: ${{ steps.current-semantic-version.major }}
          MINOR: ${{ steps.current-semantic-version.minor }}
          PATCH: ${{ steps.current-semantic-version.patch }}
          MANIFEST_SAFE_VERSION_STRING: ${{ steps.current-semantic-version.manifestSafeVersionString }}
        run: "echo major: $MAJOR minor: $MINOR patch: $PATCH manifestSafeVersionString: $MANIFEST_SAFE_VERSION_STRING"    
        shell: bash
